package gqlFilter

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"gqlFilter/ent"
)

// CreateCars is the resolver for the createCars field.
func (r *createUserInputResolver) CreateCars(ctx context.Context, obj *ent.CreateUserInput, data []*ent.CreateCarInput) error {
	// NOTE: We need to use the Ent client from the context.
	// To ensure we create all of the children in the same transaction.
	// See: Transactional Mutations for more information.
	c := ent.FromContext(ctx)
	builders := make([]*ent.CarCreate, len(data))
	for i := range data {
		builders[i] = c.Car.Create().SetInput(*data[i])
	}
	todos, err := c.Car.CreateBulk(builders...).Save(ctx)
	if err != nil {
		return err
	}
	ids := make([]int, len(todos))
	for i := range todos {
		ids[i] = todos[i].ID
	}
	obj.CarIDs = append(obj.CarIDs, ids...)
	return nil
}
