// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aboutMe/ent/hobby"
	"aboutMe/ent/predicate"
	"aboutMe/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HobbyUpdate is the builder for updating Hobby entities.
type HobbyUpdate struct {
	config
	hooks    []Hook
	mutation *HobbyMutation
}

// Where appends a list predicates to the HobbyUpdate builder.
func (hu *HobbyUpdate) Where(ps ...predicate.Hobby) *HobbyUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetName sets the "name" field.
func (hu *HobbyUpdate) SetName(s string) *HobbyUpdate {
	hu.mutation.SetName(s)
	return hu
}

// AddOwnerIDs adds the "owners" edge to the User entity by IDs.
func (hu *HobbyUpdate) AddOwnerIDs(ids ...int) *HobbyUpdate {
	hu.mutation.AddOwnerIDs(ids...)
	return hu
}

// AddOwners adds the "owners" edges to the User entity.
func (hu *HobbyUpdate) AddOwners(u ...*User) *HobbyUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return hu.AddOwnerIDs(ids...)
}

// Mutation returns the HobbyMutation object of the builder.
func (hu *HobbyUpdate) Mutation() *HobbyMutation {
	return hu.mutation
}

// ClearOwners clears all "owners" edges to the User entity.
func (hu *HobbyUpdate) ClearOwners() *HobbyUpdate {
	hu.mutation.ClearOwners()
	return hu
}

// RemoveOwnerIDs removes the "owners" edge to User entities by IDs.
func (hu *HobbyUpdate) RemoveOwnerIDs(ids ...int) *HobbyUpdate {
	hu.mutation.RemoveOwnerIDs(ids...)
	return hu
}

// RemoveOwners removes "owners" edges to User entities.
func (hu *HobbyUpdate) RemoveOwners(u ...*User) *HobbyUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return hu.RemoveOwnerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HobbyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HobbyUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HobbyUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HobbyUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hu *HobbyUpdate) check() error {
	if v, ok := hu.mutation.Name(); ok {
		if err := hobby.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hobby.name": %w`, err)}
		}
	}
	return nil
}

func (hu *HobbyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(hobby.Table, hobby.Columns, sqlgraph.NewFieldSpec(hobby.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Name(); ok {
		_spec.SetField(hobby.FieldName, field.TypeString, value)
	}
	if hu.mutation.OwnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.RemovedOwnersIDs(); len(nodes) > 0 && !hu.mutation.OwnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.OwnersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hobby.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HobbyUpdateOne is the builder for updating a single Hobby entity.
type HobbyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HobbyMutation
}

// SetName sets the "name" field.
func (huo *HobbyUpdateOne) SetName(s string) *HobbyUpdateOne {
	huo.mutation.SetName(s)
	return huo
}

// AddOwnerIDs adds the "owners" edge to the User entity by IDs.
func (huo *HobbyUpdateOne) AddOwnerIDs(ids ...int) *HobbyUpdateOne {
	huo.mutation.AddOwnerIDs(ids...)
	return huo
}

// AddOwners adds the "owners" edges to the User entity.
func (huo *HobbyUpdateOne) AddOwners(u ...*User) *HobbyUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return huo.AddOwnerIDs(ids...)
}

// Mutation returns the HobbyMutation object of the builder.
func (huo *HobbyUpdateOne) Mutation() *HobbyMutation {
	return huo.mutation
}

// ClearOwners clears all "owners" edges to the User entity.
func (huo *HobbyUpdateOne) ClearOwners() *HobbyUpdateOne {
	huo.mutation.ClearOwners()
	return huo
}

// RemoveOwnerIDs removes the "owners" edge to User entities by IDs.
func (huo *HobbyUpdateOne) RemoveOwnerIDs(ids ...int) *HobbyUpdateOne {
	huo.mutation.RemoveOwnerIDs(ids...)
	return huo
}

// RemoveOwners removes "owners" edges to User entities.
func (huo *HobbyUpdateOne) RemoveOwners(u ...*User) *HobbyUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return huo.RemoveOwnerIDs(ids...)
}

// Where appends a list predicates to the HobbyUpdate builder.
func (huo *HobbyUpdateOne) Where(ps ...predicate.Hobby) *HobbyUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HobbyUpdateOne) Select(field string, fields ...string) *HobbyUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hobby entity.
func (huo *HobbyUpdateOne) Save(ctx context.Context) (*Hobby, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HobbyUpdateOne) SaveX(ctx context.Context) *Hobby {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HobbyUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HobbyUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (huo *HobbyUpdateOne) check() error {
	if v, ok := huo.mutation.Name(); ok {
		if err := hobby.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hobby.name": %w`, err)}
		}
	}
	return nil
}

func (huo *HobbyUpdateOne) sqlSave(ctx context.Context) (_node *Hobby, err error) {
	if err := huo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hobby.Table, hobby.Columns, sqlgraph.NewFieldSpec(hobby.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hobby.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hobby.FieldID)
		for _, f := range fields {
			if !hobby.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hobby.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Name(); ok {
		_spec.SetField(hobby.FieldName, field.TypeString, value)
	}
	if huo.mutation.OwnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.RemovedOwnersIDs(); len(nodes) > 0 && !huo.mutation.OwnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.OwnersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hobby.OwnersTable,
			Columns: hobby.OwnersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hobby{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hobby.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
