// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Car) Owner(ctx context.Context) (*User, error) {
	result, err := c.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Cars(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy []*CarOrder, where *CarWhereInput,
) (*CarConnection, error) {
	opts := []CarPaginateOption{
		WithCarOrder(orderBy),
		WithCarFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[0][alias]
	if nodes, err := u.NamedCars(alias); err == nil || hasTotalCount {
		pager, err := newCarPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &CarConnection{Edges: []*CarEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return u.QueryCars().Paginate(ctx, after, first, before, last, opts...)
}
