// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hobby is the predicate function for hobby builders.
type Hobby func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
